FAILED tests\test_integration\test_only_local_working_methods\test_user_relevance_classifier.py::TestClassifier::test_predict_from_vectors


=================
X_unseen_df = ['Test-Category test test'], clf = SVC(gamma='auto'), predicted_var_for_redis_key_name = 'malformed_redis_key_name'
user_id = 999999, save_testing_csv = True, bert_model = <spacy.lang.xx.MultiLanguage object at 0x000001E0CEE282B0>
col_to_combine = ['category_title', 'all_features_preprocessed', 'full_text'], testing_mode = True

    def predict_from_vectors(X_unseen_df, clf, predicted_var_for_redis_key_name, user_id=None,
                             save_testing_csv=False, bert_model=None, col_to_combine=None, testing_mode=False):
        print("X_unseen_df size:")
>       print(len(X_unseen_df.index))
E       TypeError: object of type 'builtin_function_or_method' has no len()

src\recommender_core\recommender_algorithms\user_based_algorithms\user_relevance_classifier\classifier.py:53: TypeError



--------------



